name: Docker Image CI

on:
  push:
    branches: [ "rfiorella/era5" ]
  pull_request:
    branches: [ "rfiorella/era5" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: Docker
      run: docker build . --file Dockerfile-e3sm --tag olmtci:$(date +%s)
