name: Docker Image CI

on:
  push:
    branches: [ "rfiorella/era5" ]
  pull_request:
    branches: [ "rfiorella/era5" ]

jobs:

  build:

    runs-on: ubuntu-latest
    container:
      image: serbinsh/ngeearctic_elm_containers:elm_v2-for-ngee_multiarch
      volumes:
        - elmdata:/inputdata
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Download inputdata
      run: cd /; ./scripts/download_elm_singlesite_forcing_data.sh
